base_url: "http://localhost:8000/api/public/v1"
airbyte:
  workspaceId: 849fbe0e-9e6c-455a-8c4e-b3043dac761f
source:
  name: "mssql-oltp-database"
  port: 1433
  database: "AdventureWorks2022"
  username: "SA"
  schemas:
    - "Production"
    - "Sales"
destination:
  name: "bigquery-warehouse"
  region: "us-central1"
  default_dataset_name: "AdventureWorks2022"
  gcs_bucket: "airbyte-adventureworks2022-staging-bucket"
  gcs_bucket_data_folder: "data_sync"
connection:
  name: "default-connection"
  streams:
    - name: Product
      syncMode: incremental_deduped_history
      cursorField:
        - ModifiedDate
    - name: ProductModel
      syncMode: incremental_deduped_history
      cursorField:
        - ModifiedDate
    - name: ProductCategory
      syncMode: incremental_deduped_history
      cursorField:
        - ModifiedDate
    - name: ProductSubcategory
      syncMode: incremental_deduped_history
      cursorField:
        - ModifiedDate
    - name: SalesOrderHeader
      syncMode: incremental_deduped_history
      cursorField:
        - ModifiedDate
    - name: SalesOrderDetail
      syncMode: incremental_deduped_history
      cursorField:
        - ModifiedDate
    - name: SalesTerritory
      syncMode: incremental_deduped_history
      cursorField:
        - ModifiedDate
